ddp:
  ddp_enable: True
  world_size: 4
  gpus: [0, 1, 2, 3]
  port: '12356'

model:
  num_layers: 18
  weights_init: True

  #ablation - choose between fusion model(fusion) and baseline model(fsm)
  depth_model: 'fsm'
  pose_model: 'front'

data:
  data_path: '/data/laiyan/ssd/ddad/raw_data/ddad.json'
  log_dir: './results/'
  dataset: 'ddad'
  back_context: 1
  forward_context: 1
  depth_type: 'lidar'
  cameras: ['camera_01', 'camera_05', 'camera_06', 'camera_07', 'camera_08', 'camera_09']
  train_requirements: (gt_pose, mask)
  val_requirements: (gt_pose, gt_depth, mask)

training:
  # Basic
  height: 384
  width: 640
  scales: [0]
  frame_ids: [0, -1, 1]

  # optimization
  batch_size: 1
  num_workers: 4
  learning_rate: 0.0001
  num_epochs: 20
  scheduler_step_size: 15

  # Depth synthesis
  aug_depth: False
  syn_visualize: False

  # model / loss setting
  ## Depth range
  min_depth: 1.5
  max_depth: 200.0

  ## Spatio & temporal
  spatio: True
  spatio_temporal: True

  ## Intensity align
  intensity_align: True
  temporal_intensity_align: False
  temporal_border: False
  temporal_mask: True

  ## Focal length scaling
  focal_length_scale: 300

#  flip_version: 5
# Loss hyperparams
loss:
  disparity_smoothness: 0.1 # For convergence
  spatio_coeff: 0.03
  spatio_tempo_coeff: 0.1
#  spatial_depth_consistency_loss_weight: 0.001
#  spatial_depth_consistency_type: 'pre'
#  sp_tp_recon_con_loss_weight: 0.1


eval:
  eval_batch_size: 4
  eval_num_workers: 8
  eval_min_depth: 0
  eval_max_depth: 200
  eval_visualize: False
  syn_visualize: False
  syn_idx: None

load:
  pretrain: False
  weights: 'weights_19'
  models_to_load: ['depth_net']

logging:
  early_phase: 2000
  log_frequency: 100
  late_log_frequency: 1000
  save_frequency: 1